// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNewTimer(arg1) {
  return window['go']['main']['App']['AddNewTimer'](arg1);
}

export function AddTime() {
  return window['go']['main']['App']['AddTime']();
}

export function AddTimeCustom(arg1) {
  return window['go']['main']['App']['AddTimeCustom'](arg1);
}

export function AddTimeSecondary() {
  return window['go']['main']['App']['AddTimeSecondary']();
}

export function AddTimeTertiary() {
  return window['go']['main']['App']['AddTimeTertiary']();
}

export function CreateTimer(arg1) {
  return window['go']['main']['App']['CreateTimer'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTimerList() {
  return window['go']['main']['App']['GetTimerList']();
}

export function GetTimerStatus() {
  return window['go']['main']['App']['GetTimerStatus']();
}

export function PauseTimer() {
  return window['go']['main']['App']['PauseTimer']();
}

export function RemoveExistingTimer(arg1) {
  return window['go']['main']['App']['RemoveExistingTimer'](arg1);
}

export function RemoveTime() {
  return window['go']['main']['App']['RemoveTime']();
}

export function RemoveTimeCustom(arg1) {
  return window['go']['main']['App']['RemoveTimeCustom'](arg1);
}

export function RemoveTimeSecondary() {
  return window['go']['main']['App']['RemoveTimeSecondary']();
}

export function RemoveTimeTertiary() {
  return window['go']['main']['App']['RemoveTimeTertiary']();
}

export function RenameTimer(arg1, arg2) {
  return window['go']['main']['App']['RenameTimer'](arg1, arg2);
}

export function ResetTimer() {
  return window['go']['main']['App']['ResetTimer']();
}

export function ResumeTimer() {
  return window['go']['main']['App']['ResumeTimer']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}

export function StartTimer() {
  return window['go']['main']['App']['StartTimer']();
}

export function SwitchTimer(arg1) {
  return window['go']['main']['App']['SwitchTimer'](arg1);
}

export function SwitchTimerNext() {
  return window['go']['main']['App']['SwitchTimerNext']();
}

export function SwitchTimerPrev() {
  return window['go']['main']['App']['SwitchTimerPrev']();
}
