// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {timer} from '../models';
import {main} from '../models';

export function AddNewTimer(arg1:string):Promise<number>;

export function AddTime():Promise<void>;

export function AddTimeCustom(arg1:number):Promise<void>;

export function AddTimeSecondary():Promise<void>;

export function AddTimeTertiary():Promise<void>;

export function CreateTimer(arg1:number):Promise<void>;

export function GetSettings():Promise<settings.AppSettings>;

export function GetTimerList():Promise<Array<timer.TimerInfo>>;

export function GetTimerStatus():Promise<main.TimerStatus>;

export function PauseTimer():Promise<void>;

export function RemoveExistingTimer(arg1:number):Promise<void>;

export function RemoveTime():Promise<void>;

export function RemoveTimeCustom(arg1:number):Promise<void>;

export function RemoveTimeSecondary():Promise<void>;

export function RemoveTimeTertiary():Promise<void>;

export function RenameTimer(arg1:number,arg2:string):Promise<void>;

export function ResetTimer():Promise<void>;

export function ResumeTimer():Promise<void>;

export function SaveSettings(arg1:settings.AppSettings):Promise<void>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;

export function StartTimer():Promise<void>;

export function SwitchTimer(arg1:number):Promise<void>;

export function SwitchTimerNext():Promise<void>;

export function SwitchTimerPrev():Promise<void>;
